version: "3.9"

services:
  flask_admin:
    build: ./flaskAdmin
    env_file:
      - /.env
    environment:
      - POSTGRES_PASSWORD=flask
      - POSTGRES_USER=flask
      - POSTGRES_DB=flask
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    links:
      - pg_db
    depends_on:
      - pg_db
      - consumer
      - rabbitmq
    restart: on-failure

  pg_db:
    container_name: pg_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=flask
      - POSTGRES_USER=flask
      - POSTGRES_DB=flask
    volumes:
       - ./storage/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped


  user_db:
    container_name: user_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - ./user_storage/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped

  store_server:
    build: ./StoreServer
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SERVER_MODE=dev
      - HOST=0.0.0.0
      - PORT=8080

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5


  consumer:
    container_name: 'consumer'
    build: ./consumer
    env_file:
      - /.env
    environment:
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - QUEUE_USER=guest
      - QUEUE_PASS=guest
    depends_on:
      - rabbitmq
    restart: unless-stopped


  api_gateway:
    container_name: 'api_gateway'
    build: ./Gateway
    env_file:
      - /.env
    ports:
      - "8081:8081"
    environment:
      - SERVER_MODE=dev
      - HOST=0.0.0.0
      - PORT=8081
    links:
      - user_db
      - flask_admin
      - store_server
    depends_on:
      - flask_admin
      - store_server
      - user_db
    restart: unless-stopped
